### ISSUE TITLE
Please release 1.1

### ISSUE THREAD

**Issue by zambrovski** [camunda/camunda-acm-plugin#31]
Dear @hawky-4s- 

Please build a release 1.1 out the current master branch.

**Comment by hawky-4s-** [comment]
Hi Simon,

I did the release but had to delete the already existing 1.1 tag. Please do not create tags which should be released. I changed the old tag to 1.1-rc and duplicated the release notes for 1.1.
Please make sure that everything is alright. Ping me, then I will close the maven central staging repository for 1.1.

Cheers
Christian

**Comment by zambrovski** [comment]
Looks fine.

**Comment by hawky-4s-** [comment]
Okay, released to central. Should be available in a couple of hours.
